"use client";
export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};
export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="h-screen flex justify-center items-center">
        {children}
      </div>
    </>
  );
}
