import React from "react";
import { ThemeProvider } from "@/components/theme-provider";
import "../globals.scss";
import { Nunito } from "next/font/google";

import { LayoutClient } from "./LayoutClient";
const font = Nunito({
  subsets: ["latin"],
});
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <div className="relative">
          <LayoutClient>{children}</LayoutClient>
        </div>
      </ThemeProvider>
    </>
  );
}
